# Use the official Python image from Docker Hub
FROM python:3.8-slim

# Update system and install necessary packages
RUN apt-get update && apt-get install -y \
    gcc \
    libc-dev \
    libssl-dev \
    default-libmysqlclient-dev \
    pkg-config \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Install any dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Copy the content of the local src directory to the working directory
COPY src/ ./src/

# Copy other necessary files or directories
COPY data/ ./data/

# Command to run the application
CMD ["streamlit", "run", "src/app.py",  "--server.port=8501"]

